site_name: 'TestForDevHUBImportFlow'
site_description: 'test of techdocs'
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Troubleshooting: troubleshooting.md
docs_dir: docs
plugins:
  - techdocs-core
